### ISSUE TITLE
fix: side nav bar mobile

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#122]
Mobile side nav doesn't show Get Started, SDK Reference, Reference,.. dropdowns

See image

![Screen Shot 2022-08-29 at 10 53 14 AM](https://user-images.githubusercontent.com/79019866/187230388-cb18622b-c0c7-42ec-ac4c-4fba6c86c683.png)

**Comment by JeremyTubongbanua** [comment]
@XavierChanth gentle ping,, i tried fixing this myself during FV but no luck :(

**Comment by xavierchanth** [comment]
Oh I see, I will tackle this now
