### ISSUE TITLE
chore: README.md and atsign-foundation README.md: `atsign.dev` -> `docs.atsign.com`

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#126]
# What needs to be done

atsign.dev should be docs.atsign.com in both the:
- README.md of this repository (https://github.com/atsign-foundation/docs.atsign.com/blob/trunk/README.md)
- and the README.md of the foundation page (https://github.com/atsign-foundation/.github/blob/trunk/profile/README.md)

**Comment by xavierchanth** [comment]
closed via #143
