### ISSUE TITLE
Chore: Update the onboarding step of the flutter SDK reference code lab

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/atsign.dev-3.0#130]
**Is your feature request related to a problem? Please describe.**

I noticed the onboarding step [here](https://dev3.atsign.wtf/sdk/flutter/onboarding/) is not updated to match the [at_onboarding_flutter 5.0.0 package](https://pub.dev/packages/at_onboarding_flutter).

**Describe the solution you'd like**
I would like the [onboarding step](https://dev3.atsign.wtf/sdk/flutter/onboarding/) to be updated to reflect the changes in [at_onboarding_flutter 5.0.0](https://pub.dev/packages/at_onboarding_flutter)

**Comment by PriyanshuRj** [comment]
Hey, @TylerTrott I would like to contribute to this issue please assign this to me.

**Comment by Shubhambawner** [comment]
Hey @PriyanshuRj  as you had been working on other issues as well, may I take over this one ?
