### ISSUE TITLE
docs: min sdk version mention in the docs somewhere

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#132]
## Background

Dev eng stand up Sep 1 at 8AM Pacific-

- We discussed adding the `minSdkVersion = 1.5.32` to the build.gradle into the documentation. I believe `at_onboarding_flutter` needs this for it to be used.
- Also discussed potentially adding FVM to the documentation https://fvm.app/

@yahu1031 @CynthiaPeter is this the correct description of what we discussed at stand?

**Comment by yahu1031** [comment]
@JeremyTubongbanua Not exactly though. But must be considered doing it. And we are talking about maintaining/developing apps on the same flutter-sdk version. To do it, we can use FVM.

**Comment by CynthiaPeter** [comment]
Just like what Minnu said, it's more of trying to ensure some level of consistency across applications: https://fvm.app/

**Comment by xavierchanth** [comment]
> * Also discussed potentially adding FVM to the documentation https://fvm.app/

I recommend against this, it adds yet another barrier of entry to developing on our platform. Or at most, this should be optional. The usual expectation is that developers are using stable channel.

**Comment by xavierchanth** [comment]
See https://github.com/atsign-foundation/apps/issues/720 for latest notes on versioning for Android builds.
