### ISSUE TITLE
feat: new "platform image statements"

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#135]
# "platform statements" graphics

![image](https://user-images.githubusercontent.com/79019866/194620115-e196ed4f-37c8-417c-8c01-7dbeee2e24c5.png)

We need 3 versions of "platform image statements" like the one above:

- [ ] "An open-source, full-stack platform for creating end-to-end encrypted Java apps"
- [ ] "An open-source, full-stack platform for creating end-to-end encrypted Dart/Flutter apps"
- [ ] "An open-source, full-stack platform for simplifying and securing IoT devices"

Then implement them in `/start/flutter`, `/start/java` and `/start/iot`

**Comment by xavierchanth** [comment]
@hakeemawbrey @Dariamarg can this be a Hacktoberfest issue?

**Comment by kaggrwal** [comment]
@JeremyTubongbanua @XavierChanth I would like to work on this, kindly assign this to me.

**Comment by kaggrwal** [comment]
@XavierChanth Do i have to design the images and provide them to @JeremyTubongbanua ?

**Comment by xavierchanth** [comment]
> @XavierChanth Do i have to design the images and provide them to @JeremyTubongbanua ?

Hi @kaggrwal, the lead for this issue is currently away. I will do my best to find this info. I will get it to you next week if I cannot get it today.

**Comment by JeremyTubongbanua** [comment]
Hey @kaggrwal Sorry that there was no context for this ticket.. it was assigned to people who knew what the task was.

Basically, we need images like this one, but updated with new messages and just an overall redesign.

![image](https://user-images.githubusercontent.com/79019866/194620115-e196ed4f-37c8-417c-8c01-7dbeee2e24c5.png)

We need 3 versions:

- [ ] "An open-source, full-stack platform for creating end-to-end encrypted Java apps"
- [ ] "An open-source, full-stack platform for creating end-to-end encrypted Dart/Flutter apps"
- [ ] "An open-source, full-stack platform for simplifying and securing IoT devices"
