### ISSUE TITLE
Docs nicer discord embed

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#137]
## What needs to be done
When sharing the docs site on discord, there is an automatic discord embed that is generated. For example, if someone were to share our github foundation page on discord, they get an embed that looks like this:

![image](https://user-images.githubusercontent.com/79019866/192412104-c219076c-6241-4089-948e-534719ed58bf.png)

Our current auto generated embed looks like this and could use some work (maybe better messaging, more descriptions, logo, use of our theme colors)

![image](https://user-images.githubusercontent.com/79019866/192412127-23f16d21-5254-43f1-be8e-e4c86fc3e965.png)

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by daniloff200** [comment]
I can pick this.
I think it's related to OG images, desciriptions, etc. in a header

**Comment by daniloff200** [comment]
We can add the same picture, as for github
About the title, description, perhaps, somebody has any ideas?

cc @JeremyTubongbanua

**Comment by JeremyTubongbanua** [comment]
@daniloff200 Thanks for taking interest! Just go ahead and add what text you see fit, we can always change it later..
I've assigned you to this issue =)

**Comment by TylerTrott** [comment]
@JeremyTubongbanua
