### ISSUE TITLE
Left Navbar Caps lock Titles

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev-3.0#156]
## Skills
Some of the skills you could see yourself learning & applying as you go along:

- Git/GitHub
- GoHugo
- HTML, CSS (& Bootstrap)

## What needs to be done

The side nav bar on [docs.atsign.com](docs.atsign.com) has full uppercased words. We believe it would look better if they weren’t. For example “GET STARTED” > “Get Started.”

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by aswin2108** [comment]
@TylerTrott I would like to work on this! Can you assign this to me???

**Comment by aswin2108** [comment]
@TylerTrott Hope I could work on this as a part of hacktoberfest! Could you assign this to me? Thank you!

**Comment by JeremyTubongbanua** [comment]
Hey @aswin2108 I've updated the ticket description
Thanks for your interest. Don't forget to ask for help! There are no dumb questions.

**Comment by vardhan0604** [comment]
@TylerTrott I would like to work on this for hacktoberfest! Can you assign this to me???

**Comment by aswin2108** [comment]
hey, @vardhan0604 I am already working on it, so I hope you would find another one!

**Comment by vardhan0604** [comment]
@aswin2108 sure no problem dude!!

**Comment by JeremyTubongbanua** [comment]
Thanks @vardhan0604 :)

I've added you as an assignee to this ticket @aswin2108

**Comment by aswin2108** [comment]
@TylerTrott @JeremyTubongbanua I have made a PR can you check whether it's correct or not?

**Comment by lukes-codee** [comment]
Can I take a look at this too? I have the fix working locally.

**Comment by JeremyTubongbanua** [comment]
> Can I take a look at this too? I have the fix working locally.

Looks like the work in #176 is approved @lukes-codee 
This issue should be done and closed soon. Sorry! Thank you for your interest though
