### ISSUE TITLE
Docs Landing Page Icons

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev-3.0#157]
## Skills
Some of the skills you could see yourself learning & applying as you go along:

- HTML, CSS (& Bootstrap),
- Git/GitHub
- Graphics

## What needs to be done

- Design custom icons for our [landing page](https://docs.atsign.com/)

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by PriyanshuRj** [comment]
I want to contribute to this issue, Any suggestions on what kind of logos do we require and which logos to replace?

**Comment by roannav** [comment]
The link to the landing page above is broken.   It should be https://docs.atsign.com/

**Comment by TylerTrott** [comment]
> I want to contribute to this issue, Any suggestions on what kind of logos do we require and which logos to replace?

If you navigate to our landing page, you will see that 'Learn the SDK' and 'Learn the Platform' have the same icons. We're also utilizing Font Awesome icons so it would be cool to have our own custom ones :)

**Comment by TylerTrott** [comment]
> The link to the landing page above is broken. It should be https://docs.atsign.com/

Thank you! Fixed

**Comment by depimomo** [comment]
Hello! I notice that the new icons already created, but the icons haven't been used in the website. Do you need any help on that @TylerTrott ? I'd be glad to give it a shot!
