### ISSUE TITLE
Docs Grammar and Typos

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev-3.0#158]
## Skills
Some of the skills you could see yourself learning & applying as you go along:
- Git/GitHub
- Markdown
- English

## What needs to be done
The docs site is still new so there is bound to be typos and grammatical errors. All english correction pull requests are welcome and greatly appreciated. 

## How to do it
If you see a URL with a typo, you can go to the `content/` directory and go into the corresponding the `.md` markdown file to make changes. For example, if I wanted to fix a typo in https://docs.atsign.com/sdk/flutter/introduction/, the file path would be somewhere in `content/docs/sdk/flutter/`. Sometimes you need to go into a folder and open a `index.md` file.
 
## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by krupalitrivedi** [comment]
Hello! I would like to work on this during Hacktoberfest! It would be amazing to help with the changes.

For starting:
- We can start by fixing the "Getting Started" link in the ReadMe file of the project which is currently broken
- On 'start' page of the website, the link doesn't work for "IOT" and "Flutter"
- Proper spacing in the Atmosphere Pro's - Forking the repository.

I will be trying to find the grammar errors and typos for as many pages as I can and try to update them in issue if you want before hacktoberfest! Appreciate it if you can assign the issue to me :)

**Comment by ruqaiyasattar** [comment]
Hi There! I would like to help you with this...can you guide me on how I contribute?

**Comment by ruqaiyasattar** [comment]
There is a typo mistake on "https://docs.atsign.com/sdk/"..., can you guide me how I can fix it?

**Comment by ruqaiyasattar** [comment]
One more thing..your discord has no discord group link too

**Comment by JeremyTubongbanua** [comment]
> no discord group link too

Wow my fault. This [link](https://discord.atsign.com) should work now. Thank you for pointing that out!

> There is a typo mistake on "https://docs.atsign.com/sdk/"..., can you guide me how I can fix it?

Thank you for your interest- the instructions on how to get your GitHub fork for making contributions can be found [here](https://github.com/atsign-foundation/docs.atsign.com/blob/trunk/CONTRIBUTING.md). In summary, Fork our `docs.atsign.com` repository then get the environment working on your local machine by typing `git clone <url_repo.git> .` in the directory you want your project to be. You will need [NodeJS](https://nodejs.org/en/) on your machine to run `npm install`. Once you have your fork on your machine, run `npm install` to get the necessary packages for running the developer site on your local machine. Then, make any changes, then do `git add .` and `git commit -m "refactor: fix typos"` to commit and push it with `git push origin trunk`. (I wrote these instructions from the top of my head, so just refer to the [Contributing Guidelines](https://github.com/atsign-foundation/docs.atsign.com/blob/trunk/CONTRIBUTING.md) in case I missed something)

**Comment by JeremyTubongbanua** [comment]
> Hello! I would like to work on this during Hacktoberfest! It would be amazing to help with the changes.
> 
> For starting:
> 
> * We can start by fixing the "Getting Started" link in the ReadMe file of the project which is currently broken
> * On 'start' page of the website, the link doesn't work for "IOT" and "Flutter"
> * Proper spacing in the Atmosphere Pro's - Forking the repository.
> 
> I will be trying to find the grammar errors and typos for as many pages as I can and try to update them in issue if you want before hacktoberfest! Appreciate it if you can assign the issue to me :)

Hey! Thanks so much for your interest.

I've made the first two you mentioned into issues (which can be found here: #161 and #162). Could you please elaborate on the 3rd bullet point you mentioned? 

Also if you could comment on the issues itself, I think I should be able to assign the issue to you. If you need help with anything, please ask over at our [discord](https://discord.atsign.com/) (or just reply to this issue, anything is fine).

**Comment by krupalitrivedi** [comment]
> > Hello! I would like to work on this during Hacktoberfest! It would be amazing to help with the changes.
> > For starting:
> > 
> > * We can start by fixing the "Getting Started" link in the ReadMe file of the project which is currently broken
> > * On 'start' page of the website, the link doesn't work for "IOT" and "Flutter"
> > * Proper spacing in the Atmosphere Pro's - Forking the repository.
> > 
> > I will be trying to find the grammar errors and typos for as many pages as I can and try to update them in issue if you want before hacktoberfest! Appreciate it if you can assign the issue to me :)
> 
> Hey! Thanks so much for your interest.
> 
> I've made the first two you mentioned into issues (which can be found here: #161 and #162). Could you please elaborate on the 3rd bullet point you mentioned?
> 
> Also if you could comment on the issues itself, I think I should be able to assign the issue to you. If you need help with anything, please ask over at our [discord](https://discord.atsign.com/) (or just reply to this issue, anything is fine).

For the third point: After each attached screenshot in the tutorial, the text starts without any line spaces! Do you want me to elaborate more?

![image](https://user-images.githubusercontent.com/99717469/193058612-9b34ff6f-e0d4-4527-a874-c485f313e0d8.png)

**Comment by JeremyTubongbanua** [comment]
> > > Hello! I would like to work on this during Hacktoberfest! It would be amazing to help with the changes.
> > > For starting:
> > > 
> > > * We can start by fixing the "Getting Started" link in the ReadMe file of the project which is currently broken
> > > * On 'start' page of the website, the link doesn't work for "IOT" and "Flutter"
> > > * Proper spacing in the Atmosphere Pro's - Forking the repository.
> > > 
> > > I will be trying to find the grammar errors and typos for as many pages as I can and try to update them in issue if you want before hacktoberfest! Appreciate it if you can assign the issue to me :)
> > 
> > 
> > Hey! Thanks so much for your interest.
> > I've made the first two you mentioned into issues (which can be found here: #161 and #162). Could you please elaborate on the 3rd bullet point you mentioned?
> > Also if you could comment on the issues itself, I think I should be able to assign the issue to you. If you need help with anything, please ask over at our [discord](https://discord.atsign.com/) (or just reply to this issue, anything is fine).
> 
> For the third point: After each attached screenshot in the tutorial, the text starts without any line spaces! Do you want me to elaborate more?
> 
> ![image](https://user-images.githubusercontent.com/99717469/193058612-9b34ff6f-e0d4-4527-a874-c485f313e0d8.png)

Perfectly elaborated, @krupalitrivedi .
I'll make the issue. Thanks a lot :)

**Comment by tejasjaiswal07** [comment]
hey, @TylerTrott can I please work on this issue?
assign me!
I will try to find the typos for as many pages as possible and update them in issue if you want before hacktoberfest! Appreciate it if you could assign the issue to me :)
Thank you!

**Comment by Darsh-k-Shah** [comment]
Hey @JeremyTubongbanua, I would like to help out with this throughout hacktoberfest. 
For starters, I found an issue with the Flutter and IoT link on this page. Page - https://docs.atsign.com/start/ 
![image](https://user-images.githubusercontent.com/43760615/193400314-59cacf4b-b053-4085-8685-f114024462af.png)
On clicking the above links it seems to be redirecting to the same page. Are you also seeing this issue?
If yes, hope I can work on it and resolve it. 
Thanks :)
