### ISSUE TITLE
Docs What is Atsign?

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev-3.0#159]
## Skills
Some of the skills you could see yourself learning & applying as you go along:

- HTML, CSS (& Bootstrap)
- Git/GitHub
- GoHugo
- English

## What needs to be done
On our current landing page is intimidating because we go straight into code without ever explaining what Atsign is.
A button on the landing page with text similar to “What is Atsign?” that takes them to another page explaining Atsign would be a great addition to the landing page.

## How to do it
- Create a shortcode button in `layouts/shortcodes/button/`. See the `link.html` shortcode as an example. Shortcodes are just like Flutter widgets (or React components): they are reusable pieces of UI.
- To use the shortcode, head over to the [shortcodes guide](https://docs.atsign.com/contribute/shortcodes/button/) and there you will see an example of the shortcode being used and also how to use it yourself. For example, to use the `button/link` shortcode, you simply just type `{{< button/link href="#" type="secondary" text="Secondary" >}}` into any markdown file under `content/`.
- Once you’ve created your shortcode, you can use it in the landing page in `content/docs/_index.md`.
- (Optional) Create a page explaining what (you think) Atsign is and what we do here. Do your best! Then make your shortcode button take you to this new markdown page you’ve created.

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by Ruchika30** [comment]
Hey @TylerTrott . I can take this up. Can you please assign this to me ?

**Comment by utkershrajvenshi** [comment]
I'd like to have a go at it too. May I work on this one?

**Comment by TylerTrott** [comment]
Feel free to just work on the issues and raise PR's accordingly :) Looking forward to seeing your contributions!
