### ISSUE TITLE
feat: Review Flutter SDK documentation

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#16]
lead: @XavierChanth 

- [ ] Review the present codelab
- [ ] Evaluate the content for gaps
  - [ ] ensure full at_commons coverage 
  - [ ] Notify content
  - [ ] Best practices / tips & tricks (at_utils content)
  - [ ] Tyler & Xavier's "pizza mental model"
- [ ] Create missing content

**Comment by xavierchanth** [comment]
PR39: Begin organizing & reviewing content with the dev team in some working sessions.

**Comment by ksanty** [comment]
@XavierChanth is this still an active ticket or do you have others opened now?  Unsure if this is a placeholder for future work or already underway.  TY!

**Comment by xavierchanth** [comment]
This is a placeholder for future work
