### ISSUE TITLE
Broken link 'getting started' in `README.md`

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#161]
## Summary

The 'getting started' link is broken in the [README](https://github.com/atsign-foundation/docs.atsign.com/blob/trunk/README.md)

## What needs to be done

Route the link to [here](https://docs.atsign.com/start/) instead.

## Related issues

#158

**Comment by JeremyTubongbanua** [comment]
@krupalitrivedi if you could comment in this issue, I can assign it to you =)

**Comment by krupalitrivedi** [comment]
Hello There! I'd love to work on this :)

**Comment by krupalitrivedi** [comment]
Shall I also link the repository license at the end? It gives more flexibility to the visitors of the repository.

**Comment by JeremyTubongbanua** [comment]
No thank you @krupalitrivedi 

We usually let somebody else handle the licenses.. Thank you though!

**Comment by xavierchanth** [comment]
Complete in #177
