### ISSUE TITLE
Broken buttons in `/start/`

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#162]
## Summary

Found broken buttons for "Flutter", "Java" and "IoT' in `/start/` https://docs.atsign.com/start/. The buttons take you to the wrong links

## What needs to be done

Fix URL code located in `content/docs/sdk/_index.md` (I think that's where it is).

- Flutter button should go to `start/flutter`
- Java button should go to `start/java`
- IoT button should go to `start/iot`

## Related issues

#158

**Comment by JeremyTubongbanua** [comment]
@krupalitrivedi If you could comment on this issue, I can assign it to you =)

**Comment by krupalitrivedi** [comment]
Hii! I would love to work on this!

**Comment by krupalitrivedi** [comment]
Actually found this broken code in  `content/docs/start/_index.md`
![image](https://user-images.githubusercontent.com/99717469/193423195-733dad6d-3bbb-408f-a58d-5351ee652ce2.png)

I think the links are correct but there's some mistake in the code

**Comment by JeremyTubongbanua** [comment]
@krupalitrivedi You may find the code somewhere in `layouts/`

**Comment by Kunalpal215** [comment]
Can you assign it to me ?

**Comment by AyushK-101** [comment]
I have made a PR( #190 ) regarding this issue @JeremyTubongbanua , please review it
