### ISSUE TITLE
Atmosphere Pro contribute line breaks before images

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#163]
## Summary

![image](https://user-images.githubusercontent.com/79019866/193060100-c95520fc-2d1c-4305-99dd-782403f12c1d.png).

Images should get a line break after.

## How to do it

You can use our `{{< br >}}` shortcode. Simply add that line to the `.md` file you are editing, and tada! A line break! (Shortcodes are like React components or Flutter widgets, just reusable pieces of UI. You can find more about them [here](https://docs.atsign.com/contribute/shortcodes/button/)).

**Comment by JeremyTubongbanua** [comment]
@krupalitrivedi Please comment if you'd like to work on this :) Then I can assign it to you

**Comment by krupalitrivedi** [comment]
I'd like to work on this!

Shall I make One PR for all three changes I am going to make? because they are not major changes, yet there are few changes!

**Comment by JeremyTubongbanua** [comment]
> I'd like to work on this!
> 
> Shall I make One PR for all three changes I am going to make? because they are not major changes, yet there are few changes!

Completely your choice. :)

**Comment by saket-57** [comment]
I have already began a pull request regarding this issue. PR #191 
https://github.com/atsign-foundation/docs.atsign.com/pull/191#issue-1401924345
