### ISSUE TITLE
AtClientPreference parameters state mandatory/optional

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#165]
## What needs to be done

The attributes on https://docs.atsign.com/sdk/flutter/at_client_preference/ should state mandatory/optional,, feedback taken from @ralfeus on discord.

**Comment by kaggrwal** [comment]
@JeremyTubongbanua @XavierChanth  kindly assign this to me, i would like to work on this.

**Comment by kaggrwal** [comment]
@JeremyTubongbanua Can you please help me with a list about the preferences that are mandatory and optional, so that i can marked them accordingly in documentation.

**Comment by JeremyTubongbanua** [comment]
@kaggrwal Try referring to here https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client/lib/src/preference
@tinashe404 Who can we ask about which parameters in the AtClientPreference are required/optional ?

**Comment by kaggrwal** [comment]
@JeremyTubongbanua Can i assume, all those parameters whose default value is not given [ https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client/lib/src/preference]( https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client/lib/src/preference) are mandatory ?
eg. hiveStoragePath

**Comment by JeremyTubongbanua** [comment]
> @JeremyTubongbanua Can i assume, all those parameters whose default value is not given [ https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client/lib/src/preference](https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client/lib/src/preference) are mandatory ? eg. hiveStoragePath

That would be good enough for now @kaggrwal, thank you! :)

Could you also list what the default value is on our documentation too?

**Comment by kaggrwal** [comment]
> > @JeremyTubongbanua Can i assume, all those parameters whose default value is not given [ https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client/lib/src/preference](https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client/lib/src/preference) are mandatory ? eg. hiveStoragePath
> 
> That would be good enough for now @kaggrwal, thank you! :)
> 
> Could you also list what the default value is on our documentation too?

Sure @JeremyTubongbanua , i will add the default values too.

**Comment by JeremyTubongbanua** [comment]
I believe `hiveStoragePath`, `commitLogPath` are mandatory  and `isLocalStorageRequired` should always be true so that the local secondary is always used.

( I might be wrong though, I might recall seeing that in some comment in some code I was reading )

**Comment by xavierchanth** [comment]
> `isLocalStorageRequired` should always be true so that the local secondary is always used.

Not always, but in most use-cases it is the recommended approach. (Pretty much any application that requires human interaction will recommend this to be true).

LocalStorage is not required in the context of, for example, an IoT sensor that doesn't really care about data loss. For example, a thermometer that displays the current temperature, on the other hand, if you want to keep a history of temperatures then it may be worth setting this to true.

**Comment by gkc** [comment]
Right now, I don't believe things will work **at all** unless isLocalStorageRequired is true. We have some serious tech debt here - the original intention may have been to support both, but then the platform evolved and it was clear that for most client use cases, local storage is absolutely required - not least to support offline behaviour - but there is A LOT of code cleanup required to make it true again that we support both.
