### ISSUE TITLE
Broken link in a flutter introduction docs

### ISSUE THREAD

**Issue by daniloff200** [atsign-foundation/atsign.dev-3.0#172]
**Describe the bug**
A link to Get Started Flutter Development page is broken

**To Reproduce**
Go to https://docs.atsign.com/sdk/flutter/introduction/
Try to open Get Started Flutter Development link

**Expected behavior**
I should see the get started page

**Comment by daniloff200** [comment]
Can it be marked as a hacktobefest one?

**Comment by igniti0n** [comment]
I want to take this issue, can you assign it to me?

**Comment by ShivamKumar2002** [comment]
is it fixed? if not can you assign to me?
