### ISSUE TITLE
Change strikethrough styling of visited topics from left nav pane.

### ISSUE THREAD

**Issue by Shubhambawner** [atsign-foundation/atsign.dev-3.0#180]
**Is your feature request related to a problem? Please describe.**
Strikethrough styling of visited topics from left nav pane is little annoying for visitors, The main problem is that Rader/visitor cant just go through  list already covered topics to revise through or in case he is searching something specific.

**Describe the solution you'd like**
to mark a topic visited, we can instead style the topic little differently than strikethrough, maybe little blue or purple or italicize the text... ( suggestions welcome )
I currently consider styling them little lighter color then other topics.

**Describe alternatives you've considered**
I thought of checkboxes, but those might make UI messy. Also I doubt the need of marking the visited topics, as several other standard docs don't have such feature yet.

**Additional context**
Add any other context or screenshots about the feature request here:
![image](https://user-images.githubusercontent.com/73178780/193730560-9bc2bb0e-7f5e-4b45-a989-42d5b4902a6c.png)

**Comment by Shubhambawner** [comment]
I would be grateful if this Issue gets assigned to me along with the hacktoberfest label!

**Comment by JeremyTubongbanua** [comment]
What you you think about checkboxes @XavierChanth ?

**Comment by xavierchanth** [comment]
I don't see a need for this since:

1. Adding checkboxes increases the number of clicks required by the user, when at present this is already done for you.
2. The site is statically served, I would like to avoid adding unnecessary complexity.

**Comment by Shubhambawner** [comment]
So instead we can add something like visited anchor tag styling?
(Visited links show up purple, others show up blue, something similler i wish to say)

**Comment by TylerTrott** [comment]
@Shubhambawner Feel free to work on this. I'm interested to see what you will do with this. I can see that the strikethrough can be a bit aggressive. If you could figure out a way to show that a portion of the code lab has been completed without adding unnecessary complexity and an increase of clicks by a user, that would be really cool!

**Comment by mathagician** [comment]
@TylerTrott  there is no update yet. Could let me try as well, please assign this to me.

**Comment by Shubhambawner** [comment]
There is some delay as I was engaged with some other issues herein. But however the work is in progress
