### ISSUE TITLE
Protocol Spec missing Delete Verb

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#181]
## What needs to be done

Protocol specification missing the delete verb

This is what you mentioned in stand, right @gkc ?

**Comment by gkc** [comment]
Yep - missing from this page https://docs.atsign.com/atplatform/specification/

We should take this opportunity to update the spec and incorporate all of the additions and enhancements that have been made to verbs and syntax
