### ISSUE TITLE
Unlinked Text on the Flutter Onboarding page

### ISSUE THREAD

**Issue by srini047** [atsign-foundation/atsign.dev-3.0#184]
**Describe the bug**
There is no email id linked to `email us at` on the [flutter onboarding](https://docs.atsign.com/sdk/flutter/onboarding/) page.

**To Reproduce**
- Add the correct hyperlink of the `mailto:`
- Make the changes in https://github.com/atsign-foundation/docs.atsign.com/blob/trunk/content/docs/sdk/flutter/onboarding.md

**Expected behavior**
Should redirect to the default mailing app of the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/81156510/194094842-00bb6293-9ce9-483b-b642-1e318c09120d.png)

**Comment by xavierchanth** [comment]
@tinashe404 @athandle is this something we should do?

**Comment by JeremyTubongbanua** [comment]
Great catch! @srini047 :)

@athandle @tinashe404 is there an email to add? @srini047 would love to contribute

**Comment by tinashe404** [comment]
Great catch, please use support@atsign.com

**Comment by srini047** [comment]
Sure 😊
