### ISSUE TITLE
Better SEO Descriptions on all pages.

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#186]
**Is your feature request related to a problem? Please describe.**
When embedding or discovering pages on google search, the descriptions are not very descriptive.

**Describe the solution you'd like**
Update the descriptions for all pages, potentially making a standard format for SEO descriptions.

**Describe alternatives you've considered**
N/A

**Additional context**
See #169 for more information

**Comment by Shubhambawner** [comment]
Hello, can I work upon this?

**Comment by utkershrajvenshi** [comment]
Hi @XavierChanth , I'd love to have a go at this. Could I be assigned this issue?

**Comment by xavierchanth** [comment]
Sure @Shubhambawner @utkershrajvenshi , multiple PRs can be contributed since this is a lot of work. Please use this issue to collaborate. I suggest explicitly stating each page you are working on to avoid duplicate work.

**Comment by AyushK-101** [comment]
I would like to work on thia

**Comment by AyushK-101** [comment]
I would like to work on this

**Comment by Shubhambawner** [comment]
> Sure @Shubhambawner @utkershrajvenshi , multiple PRs can be contributed since this is a lot of work. Please use this issue to collaborate. I suggest explicitly stating each page you are working on to avoid duplicate work.

It would be great if you could asign the pages, as it would be little time taking to do this by discussion

**Comment by akashgreninja** [comment]
i would like to work on this as well

**Comment by PriyanshuRj** [comment]
Hey @XavierChanth i would like to work on this issue

**Comment by JeremyTubongbanua** [comment]
@akashgreninja @PriyanshuRj @Shubhambawner @AyushK-101 @utkershrajvenshi 

Every `.md` file should have a `description:`. Please go through each file and make sure the SEO descriptions are high quality sentences. SEO descriptions are descriptions that show up when people search us up on their search engines. You might come across some descriptions that are perfectly okay to leave alone and that is fine. However, some of them are just a few words in length and some are not edited at all. Please go through them and make sure each `.md` page has a high quality SEO description.

`content/docs/atplatform/` - @akashgreninja 
`content/docs/contribute/` - @PriyanshuRj 
`content/docs/reference/` - @Shubhambawner #197 
`content/docs/sdk/` - @AyushK-101 
`content/docs/start/` - @utkershrajvenshi 
`content/docs/tutorials/` - @utkershrajvenshi

**Comment by AyushK-101** [comment]
@JeremyTubongbanua I made a PR regarding the issue, please review and suggest changes, if any

**Comment by utkershrajvenshi** [comment]
@JeremyTubongbanua @XavierChanth , have raised a PR with updated descriptions for files in assigned directories. Please review...
