### ISSUE TITLE
Protocol Spec update Notification Verb

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#198]
## What needs to be done

Update the [Protocol Specification](https://docs.atsign.com/atplatform/specification/) with new notification examples + their responses, and a new regex.

1. Notification regex to be updated with `messageType:` parameter. 

New regex to be added:
```
notify:((?<operation>update|delete):)?(messageType:(?<messageType>key|text):)?(priority:(?<priority>low|medium|high):)?(strategy:(?<strategy>all|latest):)?(latestN:(?<latestN>\d+):)?(notifier:(?<notifier>[^\s:]+):)?(ttln:(?<ttln>\d+):)?(ttl:(?<ttl>\d+):)?(ttb:(?<ttb>\d+):)?(ttr:(?<ttr>(-)?\d+):)?(ccd:(?<ccd>true|false):)?(@(?<forAtSign>[^@:\s]*)):(?<atKey>[^:@]((?!:{2})[^@])+)(@(?<atSign>[^@:\s]+))?(:(?<value>.+))?$
```

2. Add examples of `notify:messageType:text:` and their responses
3. Add the `notify:status:` verb with examples and their responses

## Support

[Discord](https://discord.atsign.com)

**Comment by Ruchika30** [comment]
are u looking into this @JeremyTubongbanua?  or I can check it out

**Comment by JeremyTubongbanua** [comment]
Sure @Ruchika30 I updated the ticket

This one is using the atProtocol, so it's going to be a bit tricky.
