### ISSUE TITLE
Search UI broken

### ISSUE THREAD

**Issue by PriyanshuRj** [atsign-foundation/atsign.dev-3.0#199]
**Describe the bug**
In the search functionality, the searches are often crossing the designated area due to a single word having size more than the provided space we can introduce word wrap here. 

**To Reproduce**
1. First I Clicked on the Search bar
2. Then I typed get
3. And then saw that the search suggestion UI is not proper

**Expected behavior**
The left aligned Bold heading should be inside the boundary

**Screenshots**
![image](https://user-images.githubusercontent.com/76838551/194723284-8b33e2a4-5cdb-4079-971c-9deedd75100a.png)

**Smartphone (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Browser chrome
 - Version 106.0.5249.103

**Comment by itsOmSarraf** [comment]
Can you assign this to me, I can work on this, also can you let me know which folder has the codes for this ?

**Comment by itsOmSarraf** [comment]
fixed it, can you let me know the folder which contains CSS, I was able to correct it using inspect element, but unable to find the codes :(

**Comment by PriyanshuRj** [comment]
@TylerTrott please have a look

**Comment by itsOmSarraf** [comment]
Yes please, its a simple tweak in CSS, but I am unable to locate the CSS file :(

**Comment by nlather** [comment]
Hi @TylerTrott , I've made a Pull Request for this issue, could you please look at it. Thanks
