### ISSUE TITLE
feat: Github Issues tracker + Feedback button

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#22]
lead: @XavierChanth 
**Is your feature request related to a problem? Please describe.**

- [ ] A feedback button accessible on all pages to quickly open a github ticket against atsign.dev. 
- [ ] Add Git/github information and links to the footer of the site.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PriyanshuRj** [comment]
Hey @XavierChanth @TylerTrott, I would like to contribute to this issue please assign this to me.

**Comment by PriyanshuRj** [comment]
Hey @TylerTrott, I would like to contribute to this issue,

**Describe the solution you'd like**

I will create a button on the top right corner of the Documentations with the link https://github.com/atsign-foundation/docs.atsign.com/issues/new/choose 
This will take the user to the create new issue page where he would be asked what kind of issue they want to create Bug/Feature/Security vulnerability.

For the footer section, I will simply add a minimal copyright portion to the footer giving the link to the GitHub repo and the other links.

**Comment by PriyanshuRj** [comment]
What all GitHub information should I add @XavierChanth

**Comment by xavierchanth** [comment]
> What all GitHub information should I add @XavierChanth

Maybe something like:
- `Last updated on <date>`
- `By <author> in <short commit id>` (commit id can link to the commit in GitHub)
