### ISSUE TITLE
Introduce CI so that we confirm that PRs are correct before merging.

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/atsign.dev-3.0#230]
**Is your feature request related to a problem? Please describe.**
#229 illustrates a case where the build was broken requiring a fix.

**Describe the solution you'd like**
Build (but don't deploy) branches for PRs.

**Comment by JeremyTubongbanua** [comment]
I can take this on if no work has been done already @cpswan @XavierChanth

**Comment by cpswan** [comment]
Go for it @JeremyTubongbanua

**Comment by xavierchanth** [comment]
Go for it!
