### ISSUE TITLE
Bring Secondary Server page in line with latest language

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/atsign.dev-3.0#233]
**Is your feature request related to a problem? Please describe.**
#227 changed 'secondary' and 'secondary server', but we still have a whole page titled [Secondary Server](https://docs.atsign.com/atplatform/secondaryserver/)

**Describe the solution you'd like**
Rename the page atServer and edit contents accordingly.

**Comment by CynthiaPeter** [comment]
Ok, got it.
