### ISSUE TITLE
FAQ - Questions to be answered by existing/new content.

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#252]
This issue is a place to list the most common/important questions that need to be answered by our site.

Action Item: Please add comments that act as good FAQ questions for creating content.

**Comment by xavierchanth** [comment]
Checked the below questions against the [FAQ doc](https://docs.google.com/document/d/16XVJmKWH6azzc_rVyLkTlN4fFo25-61NW-KAQ2eukt8/edit#).

- [x] What does Atsign do? 
- [x] What is an atSign?
- [x] What is an atServer?
- [x] How much does it cost to implement? 
- [x] What is the atProtocol? 
- [x] How does the atProtocol route data? (added)
- [x] What is the atPlatform? (added)
- [x] What are the security benefits to routing data through an atSign? (added)
- [x] How do atSigns protect my data / privacy? (added)
- [x] What does an atServer do?

**Comment by XavierChanth** [comment]
What is an atSign?

**Comment by xavierchanth** [comment]
- atSign as an address when explaining the model and diagram
- Many registrars
  - Like DNS
  - Overview of current arch
  - Overview of future arch

**Comment by gkc** [comment]
@nickelskevin has been doing a lot of work on slides which answer many of the frequent questions. We should consider how best to make those answers available on our web site.

**Comment by gkc** [comment]
@ksanty do you think maybe this ticket is a duplicate of https://github.com/atsign-foundation/at_protocol/issues/49 ?

**Comment by ksanty** [comment]
@gkc are these [the slides ](https://docs.google.com/presentation/d/1xd6rb3ugfwrkD0uJn4Tbl2j-ISH1-IhzJ5s50epEgcI/edit#slide=id.g114c779c41c_0_62)you are referring to?

**Comment by ksanty** [comment]
@XavierChanth I think we can close this ticket now?
