### ISSUE TITLE
IoT "getting started" landing page

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/atsign.dev-3.0#276]
**Describe the bug**
https://docs.atsign.com/start/iot/ needs to be overhauled

**Expected behaviors**
Something more like https://docs.google.com/document/d/1h7d55tRB1q5F8QMXne4hHwukCnwCUoms4pSoOeTA5NI/edit

**Comment by gkc** [comment]
No progress last sprint; this sprint I'm not taking any engineering tasks, my focus will be documentation

**Comment by gkc** [comment]
Almost complete, expect to get reviewed and published by Apr 6. Reducing SP to 2

**Comment by xavierchanth** [comment]
Currently in Gitbook, just needs some more eyes: https://atsign.gitbook.io/docs/start/iot
