### ISSUE TITLE
devsite 3 | Migrate dess guide images to be page type images

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#42]
**Is your feature request related to a problem? Please describe.**
Pages are currently downloaded and added at build time, when we release this site to prod they will no longer be available for download.

**Describe the solution you'd like**

- [x] Add these images using the image shortcode, and type="page" attribute.
- [x] "dess" should be all lowercase in the content.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by xavierchanth** [comment]
@Jesseadriano10 @L1AMcB @JeremyTubongbanua can one of you pick up this card?

**Comment by JeremyTubongbanua** [comment]
> @Jesseadriano10 @L1AMcB @JeremyTubongbanua can one of you pick up this card?

I can

**Comment by JeremyTubongbanua** [comment]
Working on it in #67

**Comment by JeremyTubongbanua** [comment]
All images are now downloaded locally
and no longer fetched online.

Resulting in faster image loading.
