### ISSUE TITLE
devsite 3 | blog posts page

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#44]
lead: TBD

**Is your feature request related to a problem? Please describe.**
There is no easy way to find blog posts from our dev site.

**Describe the solution you'd like**

- [ ] card/blogpost shortcode #72 
  - Given a URL, fetch the title, splash image, description, date, and byline and display in a card
  - Needs to support hashnode, medium, and possibly linkedin
- [ ] Uses a port of the full screen layout used on the showcase/community pages
- [ ] Dynamically fetch Atsign company blogs from hashnode, medium, and linkedin

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JeremyTubongbanua** [comment]
Could I take this on @XavierChanth ?

**Comment by xavierchanth** [comment]
> Could I take this on @XavierChanth ?

Sure grab some time in the afternoon on my calendar this week

**Comment by JeremyTubongbanua** [comment]
I'll be taking on card/blogpost for now, will figure out dynamic fetching later.

**Comment by JeremyTubongbanua** [comment]
#72

**Comment by xavierchanth** [comment]
legacy due to #94
