### ISSUE TITLE
devsite 3 | blurry images on dess tutorials

### ISSUE THREAD

**Issue by realvarx** [atsign-foundation/atsign.dev-3.0#61]
**Describe the bug**
Images of dess tutorials are blurry.

**To Reproduce**

1. First I Go to [https://dev3.atsign.wtf/docs/tutorials/](https://dev3.atsign.wtf/docs/tutorials/)
2. Then I Navigate to [AWS](https://dev3.atsign.wtf/docs/tutorials/dess/aws/1_introduction/) or [GCP](https://dev3.atsign.wtf/docs/tutorials/dess/gcp/1_introduction/) tutorials
3. And then click on `Next` and navigate the web

**Expected behavior**
Images should be properly displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/71457057/173845434-3bfe1acc-761a-41c1-add3-f1b1d64d29e5.png)
![image](https://user-images.githubusercontent.com/71457057/173845584-07401be5-f9ba-4293-ba33-e0c4c79e2429.png)

**Additional context**
Tested that happens both on light and dark mode, and on Chrome and Edge navigators.

**Comment by xavierchanth** [comment]
#42 should resolve this issue
