### ISSUE TITLE
devsite 3 | Control table column width?

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#68]
**Is your feature request related to a problem? Please describe.**
Is there a way to control the column width when using tables in markdown? In the image below, the regex snippet goes to another line which I could look better if there was a way to control the column width?
![image](https://user-images.githubusercontent.com/79019866/174201241-e5b8d9f6-2a43-4f88-9c29-64c8b02fabea.png)

**Comment by JeremyTubongbanua** [comment]
#64

**Comment by xavierchanth** [comment]
Not a foreseeable priority
