### ISSUE TITLE
Content for the atmosphere pro codelab refreshes quickly

### ISSUE THREAD

**Issue by Jesseadriano10** [atsign-foundation/atsign.dev-3.0#77]
**Describe the bug**

When I enter the atmosphere pro codelab page, the content for the website begins to refresh itself multiple times.

**To Reproduce**
- Visit https://dev3.atsign.wtf/docs/tutorials/atmosphere-pro/ 

**Expected behavior**
- Behaviour should be similar to my description

**Screenshots**
https://user-images.githubusercontent.com/34658202/176756403-bec5dfe6-9019-4379-8924-33a7affa6ef0.mp4

**Comment by xavierchanth** [comment]
Not a bug, the codelab tries to redirect to first page of the content. atmosphere pro codelab doesn't have any content written yet, hence the refresh loop.
