### ISSUE TITLE
GOAL: iot.atsign.dev

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#93]
[This document](https://docs.google.com/document/d/1VR-tMa0tVcXRkilcq5wrpY3gHyn2VkJ5yhNtLRbf3LU/edit#) has been used to encompass most of this work.

- [ ] Homepage
  - [x] Define content
  - [x] Refine content @thenobleone14 @XavierChanth 
  - [ ] Designs @rtilney 
  - [ ] Implement designs @XavierChanth 
- [ ] Industries section - @anthonyvprakash @Jesseadriano10 
  - [x] Layout for content @Jesseadriano10 
  - [ ] Define content
- [ ] Tools section - @L1AMcB 
  - [ ] Layout for content - in progress by @L1AMcB 
- [ ] Docs section - TBD if any work is needed
- [ ] Showcase page - @TylerTrott
  - [ ] Define demos to be included
  - [ ] Add content for each
- [ ] Partners section - @jenmonroe to define the content on these pages
  - [ ] Design area to display existing partner "badges"
  - [ ] Partner contact form or guide to connect with us

**Comment by jenmonroe** [comment]
@XavierChanth -- @tinashe404 and I discussed this today. I have an updated contract ready, and @rtilney is working on the atVerified badge/bug. I recommend pulling the Commission program out of the larger Dev program (which originally included programming, content, and events) and just launching the atVerified and Commission portions. Should we look for some time to meet, or want to work on this asynch? Thanks!

**Comment by xavierchanth** [comment]
legacy due to #94
